<a href="https://colab.research.google.com/github/aliturab99/Islamabad_House_price_prediction_ML_Project/blob/main/Zameen_com_Islamabad_Properties_Data_Science_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [67]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [68]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1i0PiCCl9dXhxMDuR47a2TOQWrsa99m650wq_hHbawHY/export?format=csv")

In [69]:
df.shape

(14775, 9)

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14775 entries, 0 to 14774
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   listing_id  14740 non-null  float64
 1   title       14775 non-null  object
 2   price_text  14775 non-null  object
 3   price_pkr   14775 non-null  int64
 4   location    14775 non-null  object
 5   area_text   14775 non-null  object
 6   area_marla  14775 non-null  float64
 7   beds        13868 non-null  float64
 8   baths       13735 non-null  float64
dtypes: float64(4), int64(1), object(4)
memory usage: 1.0+ MB

In [71]:
df.isnull().sum()

listing_id      35
title            0
price_text       0
price_pkr        0
location         0
area_text        0
area_marla       0
beds           907
baths         1040
dtype: int64

In [72]:
df.describe()

         listing_id     price_pkr    area_marla          beds         baths
count  1.474000e+04  1.477500e+04  14775.000000  13868.000000  13735.000000
mean   5.410078e+07  9.304380e+07     15.953861      4.453057      4.555661
std    1.590959e+06  1.698869e+08     47.993253      1.983534      1.806038
min    1.745226e+07  8.000000e+04      0.900000      1.000000      1.000000
25%    5.411223e+07  2.500000e+07      5.000000      3.000000      3.000000
50%    5.460245e+07  4.450000e+07      8.000000      5.000000      5.000000
75%    5.477557e+07  9.250000e+07     14.400000      6.000000      6.000000
max    5.487768e+07  4.000000e+09   1760.000000     11.000000     10.000000

In [73]:
df.head()

,listing_id,title,price_text,price_pkr,location,area_text,area_marla,beds,baths
0,54844773.0,House At Prime Location,5.5 Crore,55000000,"D-12/1, D-12",4 Marla,4.0,3.0,5.0
1,54852451.0,Luxury 3-Bedroom Apartment For Sale In Warda H...,5.15 Crore,51500000,"Warda Hamna Residencia, G-11 Markaz",8.7 Marla,8.7,3.0,3.0
2,52696760.0,One kanal Beautiful luxurious FULL FURNISHED H...,10.9 Crore,109000000,"DHA Defence Phase 2, DHA Defence",1 Kanal,20.0,5.0,6.0
3,54793832.0,1 Kanal Luxury House Most Beautiful Prime Loca...,11.9 Crore,119000000,"DHA Defence Phase 2, DHA Defence",1 Kanal,20.0,6.0,6.0
4,54798682.0,Investor Price 1 Kanal Elegant House For Sale ...,7.9 Crore,79000000,"DHA Defence Phase 3, DHA Defence",1 Kanal,20.0,5.0,6.0

In [74]:
df.isnull().sum()

listing_id      35
title            0
price_text       0
price_pkr        0
location         0
area_text        0
area_marla       0
beds           907
baths         1040
dtype: int64

In [75]:
df1 = df.drop(columns=["listing_id", "title", "price_text", "area_text"])

In [84]:
df1.isnull().sum()

price_pkr             0
location              0
area_marla            0
beds                907
baths              1040
price_per_marla       0
dtype: int64

In [85]:
df2 = df1.dropna()

In [87]:
df2

,price_pkr,location,area_marla,beds,baths,price_per_marla
0,55000000,"D-12/1, D-12",4.0,3.0,5.0,1.375000e+07
1,51500000,"Warda Hamna Residencia, G-11 Markaz",8.7,3.0,3.0,5.919540e+06
2,109000000,"DHA Defence Phase 2, DHA Defence",20.0,5.0,6.0,5.450000e+06
3,119000000,"DHA Defence Phase 2, DHA Defence",20.0,6.0,6.0,5.950000e+06
4,79000000,"DHA Defence Phase 3, DHA Defence",20.0,5.0,6.0,3.950000e+06
...,...,...,...,...,...,...
14770,7500000,"Taramrri, Islamabad",4.0,3.0,2.0,1.875000e+06
14771,15500000,"Faisal Hills - Block A, Faisal Hills",5.0,3.0,4.0,3.100000e+06
14772,17000000,"PHAF Officers Residencia, Kuri Road",4.4,3.0,2.0,3.863636e+06
14773,82500000,"Margalla Town Phase 2, Margalla Town",8.0,7.0,6.0,1.031250e+07
14774,42000000,"G-11, Islamabad",4.4,5.0,5.0,9.545455e+06

In [90]:
df2.duplicated().sum()

np.int64(2763)

In [92]:
df3 = df2.drop_duplicates()

In [94]:
display(df3.shape)
display(df3.duplicated().sum())
display(df3.isnull().sum())

(10733, 6)

np.int64(0)

price_pkr          0
location           0
area_marla         0
beds               0
baths              0
price_per_marla    0
dtype: int64